export const FETCH_REQUEST_SUBMIT = 'FETCH_REQUEST_SUBMIT';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAIL = 'FETCH_REQUEST_FAIL';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_CANCELLED = 'FETCH_USER_CANCELLED';
export const SEARCH = 'SEARCH';
export const SEARCH_DATA = 'SEARCH_DATA';
export const CANCEL_SEARCH = 'CANCEL_SEARCH';
export const LEAVE = 'LEAVE';

